### Login

#### Request

POST http://localhost:8000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "password"
}

#### Response
POST http://localhost:8000/api/auth/logout HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3MjEyNTYxODMsImV4cCI6MTcyMTI1OTc4MywibmJmIjoxNzIxMjU2MTgzLCJqdGkiOiJWTlZGd0xlb1paYWNMVDRPIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.pdzhvg_IDxZtuGVREITbhO4ItqxGz48nhXNCvdPA_Uk

###
POST http://localhost:8000/api/lead_channels HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3MjEyNzUyOTEsImV4cCI6MTcyMTI3ODg5MSwibmJmIjoxNzIxMjc1MjkxLCJqdGkiOiJRVm42MDJpUmExb2dhQ1NHIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Bym4mPdiWjXRFJp76fMYo-XqEp56gJlqUTNi_EaXGOw

{
    "name": "test"
}

###
GET http://localhost:8000/api/lead_channels HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3MjEyNzUyOTEsImV4cCI6MTcyMTI3ODg5MSwibmJmIjoxNzIxMjc1MjkxLCJqdGkiOiJRVm42MDJpUmExb2dhQ1NHIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Bym4mPdiWjXRFJp76fMYo-XqEp56gJlqUTNi_EaXGOw

###
GET http://localhost:8000/api/lead_medias HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE3MjEyODI3MjYsImV4cCI6MTcyMTI4NjMyNiwibmJmIjoxNzIxMjgyNzI2LCJqdGkiOiJkdlRJYlR0ajlpaVNpWll2Iiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.cccKmwA2kIPyKeqjhYMAPNNZjh8OFnhgXd8djnycjv0

